server:
  port: 8762
spring:
  application:
    name: eureka-cli

eureka:
  client:
    service-url:
#      defaultZone: http://148.70.132.53:8083/eureka/,http://47.106.120.119:8083/eureka/,http://localhost:8083/eureka/
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"